### ISSUE TITLE
Android - Search by asset ID

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-android#14]
As a customer, I want to be able to search assets by asset ID, so that it will be convenient to check the validness of asset ID

**AC**

- Change hint text in search field to:
  - Search by Asset ID, Name or Ticker Symbol

**Valid scenarios**

- Asset not found if there is no asset ID match with Assets located in current manage list
- full asset ID should be inputted to validate and show the asset

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] <span data-href="#aha_task_list_SORANEO-396-1" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/> [UX/UI] search by asset ID
    [https://www.figma.com/file/De7JYMgr3AJluOqhf52ts3/SN-659?node-id=0%3A1](https://www.figma.com/file/De7JYMgr3AJluOqhf52ts3/SN-659?node-id=0%3A1)
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-396

**Comment by Trezeguet1** [comment]
The new design is still not implemented.

Actual result:
![telegram-cloud-photo-size-2-5395718645067402929-y](https://github.com/sora-xor/sora-android/assets/51509139/b606e71d-0df7-4b00-a3d5-8fdbbe70df67)

Expected result:
<img width="715" alt="Screenshot 2023-11-20 at 15 14 03" src="https://github.com/sora-xor/sora-android/assets/51509139/606b3179-9ab7-4f7f-a9cd-7a1ab633987e">

**Comment by Trezeguet1** [comment]
Missing hint text in search field according to AC:
**Search by Asset ID, Name or Ticker Symbol**

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce6e9b365d22084f4c74583618692a67e8061c78/telegram-cloud-photo-size-2-5436145836489824373-y.jpg" alt="telegram-cloud-photo-size-2-5436145836489824373-y.jpg" />

**Comment by Trezeguet1** [comment]
Verified on 7.7.7-firebase (777).

There is no hint text "Search pools" on pooled assets.

![telegram-cloud-photo-size-2-5465547876928181652-y](https://github.com/sora-xor/sora-android/assets/51509139/39945ded-5379-453a-bb7b-5573550ec586)

![telegram-cloud-photo-size-2-5465547876928181651-y](https://github.com/sora-xor/sora-android/assets/51509139/77f16aa4-35fc-4670-a450-bff9264ad9f8)

**Comment by Trezeguet1** [comment]
Fixed in 3.8.1.0- firebase (190).
