### ISSUE TITLE
Android - Add token to list of favorites

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-android#17]
As a <ins>user</ins> I want to <ins>add a token to my list of favorite tokens</ins> so that <ins>I can easily see and access it from the main screen</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-634

**Comment by Trezeguet1** [comment]
Verified on 3.8.0.0 firebase (167) version.

![telegram-cloud-photo-size-2-5393475538267526590-y](https://github.com/sora-xor/sora-android/assets/51509139/9e47fcca-0d85-41e9-9ebd-f125c9bb325b)
