### ISSUE TITLE
[Bug]: Bad error on incorrect password in Google backup

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/sora-android#242]
### Preconditions

There is a backup of any account in Google

### Steps to reproduce

1. Onboarding screen - tap import account - Google
2. Select the backup from preconditions
3. Enter invalid password

### Actual behavior

See an error on the screenshot 
![photo_2023-10-18 12 08 38](https://github.com/sora-xor/sora-android/assets/118749608/1cbbd8bc-008d-45ef-9660-6bbd90bcbfc2)

### Expected behavior

Error about invalid password

### Environment

{"label"=>"Development"}

### OS version

Android

**Comment by arvifox** [comment]
@spitsynval 
https://www.figma.com/file/5kaHWqH73Ekez7RVOpH36g/%E2%9C%85-SORA-Wallet-(on-Prod)?type=design&node-id=13169-10653&mode=design&t=9CpGlaG2cjU0WGVl-4
no state for incorrect password. please check.

**Comment by spitsynval** [comment]
https://www.figma.com/file/5kaHWqH73Ekez7RVOpH36g/%E2%9C%85-SORA-Wallet-(on-Prod)?type=design&node-id=13466%3A3602&mode=design&t=OMtHYtjEyRkw31ST-1

@arvifox

**Comment by Trezeguet1** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef6aacb2e42255f1ca13efe97dca080b871e0b8e/Screenshot%202023-11-10%20at%2014.25.31.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHpEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0be35d891aa812356843fb8c0c6dcde7ec9963f4/telegram-cloud-photo-size-2-5364004086862696571-y.jpg)

**Comment by Trezeguet1** [comment]
Verified on 3.8.0.0-firebase (167) version.

We show the loader instead of the text - Incorrect password.

![telegram-cloud-photo-size-2-5393475538267526605-y](https://github.com/sora-xor/sora-android/assets/51509139/4ec01eb9-205a-4d88-9163-a66f628f0080)

**Comment by Trezeguet1** [comment]
Verified on 3.8.0.0-firebase (247) version.

Expected behavior:
There shoild be Error about invalid password.

**Comment by Trezeguet1** [comment]
Verified on 3.7.0.5-firebase (172) version.

![telegram-cloud-photo-size-2-5399973712117224231-y](https://github.com/sora-xor/sora-android/assets/51509139/ee470cb2-1a6a-4206-9b83-d343661ff88f)
