### ISSUE TITLE
[Bug]: Android - Wrong colour on Choose - Add node dialogs

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#245]
### Steps to reproduce

1. Open More menu
2. Tap Nodes button
3. Tap ANY node OR Add custom node and Add custom Node button then

### Actual behavior

User sees too dark dialog
![image](https://github.com/sora-xor/sora-android/assets/17094492/5d99f6ad-7d6c-4f0c-93f3-c2cd0d3a7faf)

### Expected behavior

Colour of this dialog the same like other dialogs

### Environment

{"label"=>"Development"}

### OS version

Android

**Comment by Trezeguet1** [comment]
Done
