### ISSUE TITLE
[Bug]: Android - In-app updates crash

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#247]
### Steps to reproduce

see Crashlytics

### Actual behavior

crash

### Expected behavior

works well

### Environment

{"label"=>"Production"}

### OS version

android 13

**Comment by Trezeguet1** [comment]
Verified on 3.7.0.1-firebase (158).

The crash no longer occurs on the latest version which was detected in Crashlytics after migrating application versions.
