### ISSUE TITLE
[Bug]: Asset local mapper crash

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#248]
### Steps to reproduce

see Crashlytics

### Actual behavior

crash

### Expected behavior

works well

### Environment

{"label"=>"Production"}

### OS version

android 13

**Comment by Trezeguet1** [comment]
Verified on Sora Develop 3.8.0.0-firebase (160) version.

The reason of crash is visible in the logs but could not be reproduced yet.
