### ISSUE TITLE
[Bug]: Android - Socket timeout on google import account

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#259]
### Steps to reproduce

1. Install the app clean
2. Tap to google import
3. Choose any account
4. Enter password
5. Proceed

### Actual behavior

During the import process app crashes
https://console.firebase.google.com/project/sora-passport-id/crashlytics/app/android:jp.co.soramitsu.sora.develop/issues/a9758b7d052638031cde0fea86caf640

### Expected behavior

User sees Create pin screen

### Environment

{"label"=>"Development"}

### OS version

Android

**Comment by Trezeguet1** [comment]
Verified on 3.7.0.1-firebase (158).

The crash no longer occurs on the latest version which was detected in Crashlytics.
