### ISSUE TITLE
Interested in team opportunities 

### ISSUE THREAD

**Issue by thinkinginbinary** [sora-xor/sora-android#26]
Hello,

I am interested in team opportunities & I am trying to find better ways to improve GH socially. Opening up discussions on more GH repos seems like a great way to socialise more as too many engineers are siloed, antisocial even. For me I am spending basically all my time on presentation work, networking now. 

I have a good chunk of blockchain engineering xp & I like the Soramitsu team diversity a lot as I noticed this maybe a year or so ago. The  team's unique geographic makeup is really nice. You can read more about me in my bio. I am also interested in living in JP.  I am currently US based. 

I have had some decent interactions with JP folks from networking around startup building, hackathons, exploring building a JP based game company previously & trying to determine ways to end homelessness, boost tourism using emerging tech(although homelessness is hard to pin down in JP due to the social taboo of it from my current understanding(esports cafes don't count) ) such as VR and Web3.

In the past I have been working on Web3/Blockchain DeFi,  Gaming, Proptech, Legaltech, Art, AI tech startups wearing every hat, designing products/pitchdecks, & developing smart contracts/API integrations/UI/UX/FS using Rust, Python, C++, Javascript, Solidity, & Java networking with people in around 30 countries mainly in the Blockchain, Web3 & startup areas/spaces.I have applied to a few teams, still early in application processes currently. 1 week in basically. From early on I decided to find ways to leverage cryptotech in ways that benefit society in comparison to moon coins which benefit some user percentage in a lottery style way. Obviously I know alot of cryptotech endeavours are grey area endeavours due to changing regulations, rules & social perceptions. I try to keep up with all of that in order to be able to build well in the space. (The failure of blockchain companies is mainly due to misstepping legally & security flaws.) . 

 I haven't met many people besides tech execs in other countries outside of JP who are up to put in the hours that I normally have towards whatever goals are being pursued although work life balance & health are obviously important also & obviously SF startup folks also are known to put in long hours for example. 

Another area I am interested in chatting with companies about is grant support for future research, projects. 

You can read more about me in my GH bio. I am also on Twitter, LI. I may start uaing Medium again. I am working on leveraging Discord once more. I am currently looking for a good team to join & I realized JP folks like international communication as much as me especially with recent diplomatic pushes. I really like the economic focus & am wanting to learn more about your team's work in that area. (I haven't fully consumed SORA domains.). 

I have noticed that few people have noticed how Web3 can be leveraged not only as a fiat counterpart but also as a fiat simulation of sorts or a middleground  between traditional fiat systems & more efficient financial systems. (Few meaning less than 1k based on web, social data.) . 

My Direct GH link: https://github.com/thinkinginbinary 
Email: rolesearching.lmq0j@slmail.me

Hopefully this is a good conversation starter. ✨️

**Comment by Tieumsan** [comment]
Hi @thinkinginbinary , thank you for the introduction. One distinction I cannot stress enough is the one between SORA and SORAMITSU. 
SORA is a vision and economic system, part of which is the SORA blockchain, which is the financial infrastructure enabling the SORA economy. 
SORAMITSU is a company working on several projects and one of the many contributors to SORA. 

Reading your introduction, I couldn't be sure to understand whether you are interesting in working for SORA or for SORAMITSU. 
In the first case, I would invite you to join and share with our community, for example through our Telegram chats (https://t.me/sora_xor).
In the latter case, I would invite you to apply directly on the Career website of SORAMITSU the company could follow up with you on your interests (https://soramitsu.freshteam.com/jobs).
