### ISSUE TITLE
Android - Remove Stake on Pool

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#279]
As a <ins>staker on my liquidity provision</ins> I want to <ins>remove my stake on my pooled assets</ins> so that <ins>I can fully control my assets</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-603

**Comment by Trezeguet1** [comment]
Edit farm does not reset to zero the first time - it worked the second time.
If the application is open for a long time - subscriptions disappear and the percentages change and are no longer displayed exactly.
We need to fix subscriptions on Farming - apparently there is an overload of subscriptions and we need to check how many connections there are.

**Comment by Trezeguet1** [comment]
https://github.com/sora-xor/sora-android/assets/51509139/1d18c7a3-5995-4985-a69b-5cb20d005668
