### ISSUE TITLE
Android - See LP staking reward yields

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-Android#280]
<p>As a <u>liquidity provider</u> I want to <u>see the staking reward yields I got from staking my liquidity on pools to which I provide liquidity</u> so that <u>I can understand how profitable staking my LP is/was as part of my portfolio strategy</u>.</p>

**Comment by Trezeguet1** [comment]
Verified on latest Solution version.

Acceptance criteria were checked and bugs were created within individual tasks.
