### ISSUE TITLE
Android - Stake on Pool

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#281]
<p>As a <u>liquidity provider</u> I want to <u>stake my pooled assets</u> so that <u>I can get rewards from putting my assets to work for the ecosystem</u>.</p>

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-601

**Comment by Trezeguet1** [comment]
The design has been reviewed.

Verified on Soralution demo version from Store by 22 December.
