### ISSUE TITLE
Android - Claim Rewards for Stake on Pool

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#282]
As a <ins>staker on my liquidity provision</ins> I want to <ins>claim my rewards for staking on pools</ins> so that <ins>I can get rewarded for putting my assets to work for the SORA ecosystem</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-605

**Comment by Trezeguet1** [comment]
Verified on Soralution demo version from Store by 22 December.

![telegram-cloud-photo-size-2-5210726032737424684-y](https://github.com/sora-xor/sora-android/assets/51509139/ccfe789c-b8c7-41af-bfc6-ea9f8e8735c1)
