### ISSUE TITLE
[Bug]: Price trend percents UI issue for Arabic language

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#284]
### Preconditions

Price trend changed more than 100%

### Steps to reproduce

Open the app

### Actual behavior

![image](https://github.com/sora-xor/sora-android/assets/17094492/8ccd0502-1dfc-4438-bbf0-e30c10441681)

### Expected behavior

Price trend shows in one line

### Environment

{"label"=>"Development"}

### OS version

Android

**Comment by Trezeguet1** [comment]
Verified on 3.8.0.0-firebase (167) version.

![telegram-cloud-photo-size-2-5399973712117224200-y](https://github.com/sora-xor/sora-android/assets/51509139/1b753985-94e7-4809-9f5c-d87b5b31ae42)
