### ISSUE TITLE
[Tech]: Change mechanism of theme change without pin code

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#298]
### Problem statement

Now when user changes the theme he needs to input pin or does biometry auth

https://github.com/sora-xor/sora-android/assets/17094492/220b5f33-246e-4107-a0b5-401fe164f9bd

### Acceptance Criteria

When user change theme he sees it immediately 

### Definition of Done

When user change theme he sees it immediately

**Comment by Trezeguet1** [comment]
Implemented and now you don’t need to enter a password to change the theme.
Verified on Soralution 3.8.1 (13) version.
