### ISSUE TITLE
[Tech]: Fix fee showing according the new refactoring on Subquery 

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#304]
### Problem statement

![image](https://github.com/sora-xor/sora-android/assets/17094492/3e185efa-0e84-4093-85c2-436320ca3955)

### Acceptance Criteria

1. Fees shows accurate

### Definition of Done

User sees actual fee

**Comment by Trezeguet1** [comment]
It is necessary to roll back the subquery changes related to fee and add fresh subquery logic for transactions.

**Comment by Trezeguet1** [comment]
Verified on 3.8.4.0 Soralution Beta version.

![telegram-cloud-photo-size-2-5449593585252029681-y](https://github.com/sora-xor/sora-android/assets/51509139/8d4eb5d7-0b40-4077-aa1d-465fcced7d20)
