### ISSUE TITLE
[Tech]: Hide fees info on Receive transaction

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#323]
### Problem statement

Now users complain if they see fees on receive side, tx fee was paid by sender side.
![image](https://github.com/sora-xor/sora-android/assets/17094492/aa1fa90c-323b-4f93-b45b-d05fb9f4178b)

### Acceptance Criteria

1. User shouldn't sees Fee info on receive tx

### Definition of Done

User doesn't see Fee info on receive tx

**Comment by Trezeguet1** [comment]
Verified on 7.7.7-firebase (777).

![telegram-cloud-photo-size-2-5465547876928181642-y](https://github.com/sora-xor/sora-android/assets/51509139/885fccc3-fa55-4d02-9600-48b8f8184cc6)
