### ISSUE TITLE
Show Demeter tx history

### ISSUE THREAD

**Issue by arvifox** [sora-xor/sora-android#328]

**Comment by Trezeguet1** [comment]
Verified on SORA_Wallet_3.8.1.0-debug_124_soralution_debug version.

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1IrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1761974ae8b4e6f44b37b94776c9a23c9d61b75c/telegram-cloud-photo-size-2-5199827840986633076-y.jpg" alt="telegram-cloud-photo-size-2-5199827840986633076-y.jpg" />
