### ISSUE TITLE
[Bug]: Android - Assets are shown instead of currencies in Search mode on Explore tab

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/sora-android#385]
### Preconditions

A wallet is connected

### Steps to reproduce

1. Go to Explore page
2. Type "Sora" in the Search field
3. Try to tap any search item

### Actual behavior

Assets are shown instead of currencies (balance, fiat price, etc)
![photo_2024-01-19 11 45 27](https://github.com/sora-xor/sora-android/assets/118749608/ea937ac4-c7bc-4d7b-a383-2d20ec8699a4)

### Expected behavior

Currencies are shown

![photo_2024-01-19 11 45 33](https://github.com/sora-xor/sora-android/assets/118749608/f9453131-bc1f-45a6-ba5e-c0837ee471c6)

### Environment

{"label"=>"Development"}

**Comment by Trezeguet1** [comment]
Verified on 3.8.1.1-firebase(253) develop version.
