### ISSUE TITLE
[Bug]: Seed phrase doesn’t cut to 64 symbols

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#395]
### Steps to reproduce

1. Open account options
2. Tap show RAW seed

### Actual behavior

User sees too long seed
![image](https://github.com/sora-xor/sora-android/assets/17094492/b6bac716-4fce-4b22-9c6d-300d8c2f72ab)

### Expected behavior

User sees 64 symbol seed

### Environment

{"label"=>"Production"}

### OS version

Android

**Comment by Trezeguet1** [comment]
Verified on 3.8.4.0 Soralution Beta version.

![telegram-cloud-photo-size-2-5449593585252029667-y](https://github.com/sora-xor/sora-android/assets/51509139/7bb59c46-1cc9-4ea8-94ef-bd76011af8f7)
