### ISSUE TITLE
Happy to contribute

### ISSUE THREAD

**Issue by herou** [sora-xor/Sora-Android#4]
Hello, 

I am an android developer interested in blockchain who find this app a good place to contribute.

Any documentation?

**Comment by Huge** [comment]
This seems dead/stalled.'(
Otherwise I'd expect a release already.

**Comment by pgolovkin** [comment]
> This seems dead/stalled.'(
> Otherwise I'd expect a release already.

We're workin on a big update for SORA2. So the project is alive. Please check the testnet https://t.me/sora_testnet
https://polkaswap.medium.com/sora-testnet-with-hashi-eec54eb057e1

**Comment by dantez11** [comment]
Good

**Comment by Viokeoke** [comment]
Hello, How can I collab with your project? I am an Android developer too and I want to go into this crypto world collaborating with your awesome project

**Comment by pgolovkin** [comment]
> Hello, How can I collab with your project? I am an Android developer too and I want to go into this crypto world collaborating with your awesome project

Hello @Viokeoke! Glad to hear. Collaboration will be good. Do you have any proposals or issues that you'd like to implement or fix?

**Comment by Viokeoke** [comment]
> > Hello, How can I collab with your project? I am an Android developer too and I want to go into this crypto world collaborating with your awesome project
> 
> Hello @Viokeoke! Glad to hear. Collaboration will be good. Do you have any proposals or issues that you'd like to implement or fix?

Hello @pgolovkin I am going to see if I can improve the current project or solve some issues. Do you have any Jira or similar to see the current issues? 
The current branch master is the latest? I did not see any tag or branch with new features.

**Comment by pgolovkin** [comment]
> > > Hello, How can I collab with your project? I am an Android developer too and I want to go into this crypto world collaborating with your awesome project
> > 
> > 
> > Hello @Viokeoke! Glad to hear. Collaboration will be good. Do you have any proposals or issues that you'd like to implement or fix?
> 
> Hello @pgolovkin I am going to see if I can improve the current project or solve some issues. Do you have any Jira or similar to see the current issues?
> The current branch master is the latest? I did not see any tag or branch with new features.

We do have Jira, but it's not opened for now. Also the current branch is not up to date. 
We're working now on involving community in development. But currently infrastructure is not ready, apologise.
This question will have been resolved in a month. Let's stay in touch. I'll keep this ticket opened.

You can start from building the application, please, let me know if you find any problems.

Thanks a lot for cooperation!
