### ISSUE TITLE
[Tech]: Make changes into LP Fee information according new returned from quote

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-android#405]
### Problem statement

We have a task which will change the data of quote - https://github.com/sora-xor/sora2-network/issues/925
Design task - https://app.zenhub.com/workspaces/sora-wallet---development-6529439e287e980cb41b583b/issues/zh/22
Now we have XOR token only in LP Fee but we will have more tokens on fees for swaps.
For example for swap XST-XSTUSD we will have fee in XST.
For XOR-XSTUSD we will have 2 tokens, XOR and XST.
For XSTUSD-DAI it can be 3 tokens like XOR, XSTUSD, XST.

### Acceptance Criteria

App shows LP Fee by the asset which it receives from quote RPC.

### Definition of Done

- User sees LP Fee by the asset which it receives from quote RPC
- App can work with old and new type of RPC

**Comment by arvifox** [comment]
[ios task](https://github.com/sora-xor/sora-ios/issues/432)

**Comment by Trezeguet1** [comment]
Verified on 3.8.4.0 Soralution Beta version.

![telegram-cloud-photo-size-2-5449677599107306639-y](https://github.com/sora-xor/sora-android/assets/51509139/cd591c4c-4463-4bed-8934-af532de8249a)

![telegram-cloud-photo-size-2-5449677599107306640-y](https://github.com/sora-xor/sora-android/assets/51509139/84888dc5-de1a-42b2-86f3-c9a9efc23ba1)
