### ISSUE TITLE
No option to use pre-existing Ethereum address

### ISSUE THREAD

**Issue by kilogold** [sora-xor/Sora-Android#6]
I downloaded the app on Android and followed setup steps.
I was not instructed to provide my existing Ethereum address for the in-app wallet.

I also have no option to add/remove/replace the Ethereum address - I can only hide.
![image](https://user-images.githubusercontent.com/1028926/110192687-5fe83100-7de4-11eb-82a1-a96e3307aa29.png)

Will this impact Val Airdrop eligibility?
Are there any workarounds to register my existing Ethereum address?

**Comment by pgolovkin** [comment]
Hey.
The idea is to use the same passphrase for both accounts (Ethereum and SORA). We haven't planned to release a feature for adding a custom Ethereum acccount.

This won't impact VAL airdrop.

**Comment by kilogold** [comment]
I see...
So this dual-linked passphrase is basically in order to generate a single private key for both networks, correct?

I suppose the HASHI bridge will utilize these addresses for transferring between Ethereum & Sora networks, correct?

**Comment by pgolovkin** [comment]
HASHI bridge utilize SORA private key for signing SORA transaction and Ethereum private key for signing Ethereum transaction.

**Comment by kilogold** [comment]
I see. I think I understood. Thanks!
